version: "3"
services:
  app:
    container_name: go-fuse-sample
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - .:/workspace:cached
      - ~/.ssh:/root/.ssh
      - ~/.gitconfig:/root/.gitconfig
